version: "3.3"
services:
  crawler:
    build: .
    container_name: crawler
    # ports:
    #     - 4000:4000
    privileged: true
    volumes: 
      - .:/usr/src/app
    command: python3 crawl_youtube/main.py
    stdin_open: true # docker run -i
    tty: true        # docker run -t